---
#
# d/w/o release pipeline params
#
build_jupyterlabdemo:
  image_name: lsstsqre/jld-lab
validate_drp:
  no_push: false
documenteer:
  publish: true
#
# general config values
#
awscli:
  pypi:
    version: &awscli_ver '1.14.61'
  dockerfile:
    github_repo: lsst-sqre/docker-awscli
    git_ref: master
  docker:
    repo: lsstsqre/awscli
    tag: *awscli_ver
codekit:
  pypi:
    version: &codekit_ver '7.1.0'
  dockerfile:
    github_repo: lsst-sqre/sqre-codekit
    git_ref: master
  docker:
    repo: lsstsqre/codekit
    tag: *codekit_ver
