---
#
# d/w/o release pipeline params
#
build_jupyterlabdemo:
  image_name: lsstsqre/jld-lab
validate_drp:
  no_push: false
documenteer:
  publish: true
#
# general config values
#
awscli:
  pypi:
    version: &awscli_ver '1.14.61'
  github_repo: lsst-sqre/docker-awscli
  # branch of Dockerfile
  git_ref: master
  docker_repo: lsstsqre/awscli
  docker_tag: *awscli_ver
codekit:
  pypi:
    version: &codekit_ver '7.1.0'
  github_repo: lsst-sqre/sqre-codekit
  # branch of Dockerfile
  git_ref: master
  docker_repo: lsstsqre/codekit
  docker_tag: *codekit_ver
