---
#
# d/w/o release pipeline params
#
build_jupyterlabdemo:
  image_name: lsstsqre/jld-lab
validate_drp:
  no_push: false
documenteer:
  publish: true
#
# general config values
#
awscli:
  github_repo: lsst-sqre/docker-awscli
  # branch of Dockerfile
  github_ref: master
  docker_repo: lsstsqre/awscli
  version: '1.14.61'
