---
sudo: false
language: c
matrix:
  include:
    - env: TEST=yamllint
      language: c
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
